title: Deepan Kumar
description: Staff Engineer Portfolio
baseurl: "/portfolio"
url: "https://deepanhp.github.io"

# Build settings
markdown: kramdown
source: .
destination: ./_site
layouts_dir: _layouts
include:
  - "*.html"
  - "*.erb"
  - "*.css"
  - "*.js"
  - "*.jpg"
  - "*.png"
  - "*.gif"
  - "*.svg"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - tmp/
  - log/
  - .git/
  - .github/
  - bin/
  - config/
  - db/
  - lib/
  - storage/
  - test/
  - .gitignore
  - .ruby-version
  - config.ru
  - package.json
  - yarn.lock
  - Rakefile 