name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      RAILS_CREDENTIALS_KEY: ${{ secrets.RAILS_CREDENTIALS_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.4'
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Setup credentials
        run: |
          echo "$RAILS_CREDENTIALS_KEY" > config/credentials/production.key

      - name: Build site
        run: |
          bundle exec rake assets:precompile
          bundle exec rake assets:clean
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site