name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  github-pages:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.4'
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Build Rails assets
        run: |
          bundle exec rake assets:precompile
          bundle exec rake assets:clean

      - name: Prepare site content
        run: |
          # Create temp directory for site content
          mkdir -p temp_site
          
          # Copy main HTML files
          cp -r app/views/home/* temp_site/
          cp -r app/views/layouts/* temp_site/_layouts/
          
          # Copy assets
          mkdir -p temp_site/assets
          cp -r public/assets/* temp_site/assets/ || true
          cp -r app/assets/images/* temp_site/assets/ || true
          
          # Copy index file
          cp index.html temp_site/
          
          # Move everything to root
          rm -rf _site
          mv temp_site _site

      - name: Build Jekyll site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          enable_jekyll: true