name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  github-pages:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.4'
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Build Rails assets
        run: |
          bundle exec rake assets:precompile
          bundle exec rake assets:clean

      - name: Prepare site directory
        run: |
          # Create site directory
          mkdir -p _site
          
          # Copy index.html
          cp index.html _site/
          
          # Create directories for other pages
          mkdir -p _site/about
          mkdir -p _site/projects
          mkdir -p _site/contact
          mkdir -p _site/surprise
          
          # Copy view files as HTML
          cp app/views/home/about.html.erb _site/about/index.html
          cp app/views/home/projects.html.erb _site/projects/index.html
          cp app/views/home/contact.html.erb _site/contact/index.html
          cp app/views/home/surprise.html.erb _site/surprise/index.html
          
          # Copy assets
          mkdir -p _site/assets
          cp -r public/assets/* _site/assets/ || true
          cp -r app/assets/images/* _site/assets/images/ || true
          
          # Copy layout files
          mkdir -p _site/_layouts
          cp -r app/views/layouts/* _site/_layouts/

      - name: Process ERB files
        run: |
          # Create script to process ERB files
          cat > process_erb.rb << 'EOL'
          require 'erb'
          require 'fileutils'

          def process_erb_files(dir)
            Dir.glob("#{dir}/**/*.html").each do |file|
              next if file.include?('_layouts')
              content = File.read(file)
              # Remove ERB tags and Rails-specific code
              processed = content.gsub(/<%=?\s*.*?\s*%>/, '')
              File.write(file, processed)
            end
          end

          process_erb_files('_site')
          EOL

          # Run the script
          ruby process_erb.rb

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site